version: '3.1'
services:
  vx-dungeon-mongo:
    image: mongo:4.2.6-bionic
    container_name: vx-dungeon-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vx-dungeon
      MONGO_INITDB_ROOT_PASSWORD: vx-dungeon
      MONGO_INITDB_DATABASE: vx-dungeon
    ports:
      - 27017:27017
    volumes:
      - ../config/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../data/db:/data/db

  vx-dungeon-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - vx-dungeon-mongo
    ports:
      - 8080
    container_name: vx-dungeon-app

  vx-dungeon-nginx:
    image: nginx:1.13.7
    container_name: vx-dungeon-nginx
    depends_on:
      - vx-dungeon-app
    volumes:
      - ../config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
