version: '3.1'
services:
  mongo:
    image: mongo:4.2.6-bionic
    container_name: vx-dungeon-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vx-dungeon
      MONGO_INITDB_ROOT_PASSWORD: vx-dungeon
      MONGO_INITDB_DATABASE: vx-dungeon
    ports:
      - 27017:27017
    volumes:
      - ../config/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../data/db:/data/db

  vx-dungeon-app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: vx-dungeon-app
