name: vx-dungeon-app-dev

on:
  push:
    branches: [ VX-1 ]
  pull_request:
    branches: [ VX-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libfuzzy-dev
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r src/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        cd src
        python -m unittest discover -s tests
    - name: Login to DockerHub Registry
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: |
        echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag 0bscurec0de/vx-dungeon:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: |
        docker push 0bscurec0de/vx-dungeon:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: |
        docker build . --file Dockerfile --tag 0bscurec0de/vx-dungeon:latest
    - name: Push the latest Docker image
      run: |
        docker push 0bscurec0de/vx-dungeon:latest
